//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicWallyMisr
{
    using System;
    using System.Collections.Generic;
    
    public partial class Imaging
    {
        public System.Guid id { get; set; }
        public Nullable<System.DateTime> ImageDate { get; set; }
        public string ImageCenter { get; set; }
        public string TypeofImage { get; set; }
        public string Site { get; set; }
        public string Comments { get; set; }
        public string ImageName { get; set; }
        public Nullable<System.Guid> VisitId { get; set; }
    
        public virtual visit visit { get; set; }
    }
}
