//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicWallyMisr
{
    using System;
    using System.Collections.Generic;
    
    public partial class patient
    {
        public patient()
        {
            this.surgicalHistories = new HashSet<surgicalHistory>();
        }
    
        public System.Guid id { get; set; }
        public string name { get; set; }
        public string diagnosis { get; set; }
        public string diagnosisCode { get; set; }
        public string notes { get; set; }
        public string masterStatus { get; set; }
        public Nullable<System.DateTime> dateofDiagnosis { get; set; }
        public string firstStatus { get; set; }
        public Nullable<System.DateTime> dateofRelapse { get; set; }
        public Nullable<System.DateTime> firstPresentationDate { get; set; }
        public Nullable<System.DateTime> birthDate { get; set; }
        public Nullable<System.Guid> doctorId { get; set; }
        public Nullable<int> age { get; set; }
        public string gender { get; set; }
        public string referredFrom { get; set; }
        public string education { get; set; }
        public string nationality { get; set; }
        public string maritalStatus { get; set; }
        public string occupation { get; set; }
        public Nullable<int> noofChildren { get; set; }
        public Nullable<int> ageofOldest { get; set; }
        public Nullable<int> ageofYoungest { get; set; }
        public string phone1 { get; set; }
        public string phone2 { get; set; }
        public string phone3 { get; set; }
        public string email { get; set; }
        public string governorate { get; set; }
        public string address { get; set; }
        public string relationName { get; set; }
        public string relation { get; set; }
        public string relationPhone1 { get; set; }
        public string relationPhone2 { get; set; }
        public string relationPhone3 { get; set; }
        public string relationAddress { get; set; }
        public string relationGovernorate { get; set; }
        public string demographic { get; set; }
        public string demographicType { get; set; }
        public string demographicSince { get; set; }
        public Nullable<int> packsNumber { get; set; }
        public bool alcoholIntake { get; set; }
        public string menstrual { get; set; }
        public bool LMP { get; set; }
        public Nullable<System.DateTime> LMPDate { get; set; }
        public string contraception { get; set; }
        public bool pregnancyatDiagnosis { get; set; }
        public string RelationDisease { get; set; }
        public Nullable<int> RelationAgeatDiagnosis { get; set; }
        public bool Diabetes { get; set; }
        public Nullable<System.DateTime> diabetesSince { get; set; }
        public string diabetesType { get; set; }
        public bool hypertension { get; set; }
        public Nullable<System.DateTime> hypertensionSince { get; set; }
        public string hypertensionType { get; set; }
        public bool hepatitiesC { get; set; }
        public Nullable<System.DateTime> hepatitiesCSince { get; set; }
        public string hepatitiesCType { get; set; }
        public bool bilharziasis { get; set; }
        public Nullable<System.DateTime> bilharziasisSince { get; set; }
        public string bilharziasisType { get; set; }
        public bool cardiac { get; set; }
        public Nullable<System.DateTime> cardiacSince { get; set; }
        public string cardiacType { get; set; }
        public bool autoImmuneDisease { get; set; }
        public Nullable<System.DateTime> autoImmuneDiseaseSince { get; set; }
        public string autoImmuneDiseaseType { get; set; }
        public bool allergy { get; set; }
        public Nullable<System.DateTime> allergySince { get; set; }
        public string allergyType { get; set; }
    
        public virtual SystemPerson SystemPerson { get; set; }
        public virtual ICollection<surgicalHistory> surgicalHistories { get; set; }
    }
}
