//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicWallyMisr
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> groupId { get; set; }
        public Nullable<System.Guid> tableId { get; set; }
        public bool canAdd { get; set; }
        public bool canEdit { get; set; }
        public bool canDelete { get; set; }
        public bool canRead { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Table Table { get; set; }
    }
}
