//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicWallyMisr
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public System.Guid id { get; set; }
        public string patientName { get; set; }
        public Nullable<System.DateTime> fromTime { get; set; }
        public Nullable<System.DateTime> toTime { get; set; }
        public string reservationType { get; set; }
        public string notes { get; set; }
        public string status { get; set; }
        public Nullable<System.Guid> doctorId { get; set; }
        public string roomNumber { get; set; }
    
        public virtual SystemPerson SystemPerson { get; set; }
    }
}
