//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicWallyMisr
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemPerson
    {
        public SystemPerson()
        {
            this.patients = new HashSet<patient>();
            this.Reservations = new HashSet<Reservation>();
            this.visits = new HashSet<visit>();
        }
    
        public System.Guid id { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string gender { get; set; }
        public string religion { get; set; }
        public string nationality { get; set; }
        public string maritalStatus { get; set; }
        public string insuranceNo { get; set; }
        public string SSN { get; set; }
        public Nullable<System.DateTime> DateofBirth { get; set; }
        public string Phone { get; set; }
        public string mobile1 { get; set; }
        public string mobile2 { get; set; }
        public string place { get; set; }
        public string cv { get; set; }
        public Nullable<System.DateTime> joinDate { get; set; }
        public Nullable<System.DateTime> leaveDate { get; set; }
        public string leaveReason { get; set; }
        public string scientificDegree { get; set; }
        public string Type { get; set; }
        public Nullable<System.Guid> jobId { get; set; }
        public Nullable<System.Guid> specializationId { get; set; }
    
        public virtual Job Job { get; set; }
        public virtual ICollection<patient> patients { get; set; }
        public virtual ICollection<Reservation> Reservations { get; set; }
        public virtual Specialization Specialization { get; set; }
        public virtual ICollection<visit> visits { get; set; }
    }
}
