//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicWallyMisr
{
    using System;
    using System.Collections.Generic;
    
    public partial class visit
    {
        public visit()
        {
            this.Complaints = new HashSet<Complaint>();
            this.Endoscopies = new HashSet<Endoscopy>();
            this.examinations = new HashSet<examination>();
            this.Imagings = new HashSet<Imaging>();
            this.Laboratories = new HashSet<Laboratory>();
            this.prescriptions = new HashSet<prescription>();
        }
    
        public System.Guid id { get; set; }
        public Nullable<System.DateTime> visitDate { get; set; }
        public string visitStatus { get; set; }
        public string visitSite { get; set; }
        public string complaintType { get; set; }
        public string PresentHistory { get; set; }
        public string decision { get; set; }
        public string requestedInvestigations { get; set; }
        public string GeneralAppearance { get; set; }
        public string mentality { get; set; }
        public string Built { get; set; }
        public bool Pallor { get; set; }
        public bool jaundice { get; set; }
        public bool cyanosis { get; set; }
        public bool postureDuringWalking { get; set; }
        public bool postureStanding { get; set; }
        public bool postureSitting { get; set; }
        public bool postureLyingSupineorPhone { get; set; }
        public string vitalSigns { get; set; }
        public Nullable<System.Guid> DoctorId { get; set; }
        public Nullable<System.Guid> patientId { get; set; }
    
        public virtual ICollection<Complaint> Complaints { get; set; }
        public virtual ICollection<Endoscopy> Endoscopies { get; set; }
        public virtual ICollection<examination> examinations { get; set; }
        public virtual ICollection<Imaging> Imagings { get; set; }
        public virtual ICollection<Laboratory> Laboratories { get; set; }
        public virtual patient patient { get; set; }
        public virtual ICollection<prescription> prescriptions { get; set; }
        public virtual SystemPerson SystemPerson { get; set; }
    }
}
